config/routes.rb
Rails.application.routes.draw do
  get "inscription", to: "inscriptions#new"
  post "inscription", to: "inscriptions#create"

  post "user", to: "user#index"
  
  resources :user do
        patch :toggle_payed_status
  end
  
  root 'inscriptions#new'
end
 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    after_create :welcome_send

    validates :name, presence: {message: ": Merci de mettre ton nom"}
    validates :first_name, presence: {message: ": Merci de mettre ton prénom"}
    validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: ": L'adresse email doit être valide"}, uniqueness: {message: ": Cette adresse email est déjà utilisé"}
    validates :payed, presence: {message: ": Merci de confirmer ta participation financière"}

    def welcome_send
        UserMailer.welcome_email(self).deliver_now
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/inscriptions_controller.rb
class InscriptionsController < ApplicationController
    

    

    def new
        @user = User.new
    end

    def create
       @user = User.new(user_params)
       if @user.save
        redirect_to "https://lydia-app.com/collect/31121-25-ans-jb-thom/fr", notice: "Allééééé làà !"
       else
        render :new
       end 
    end

    private

    def user_params
        params.required(:user).permit(:name, :first_name, :email, :payed)
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
    def index
        @user = User.all
    end

    def toggle_payed_status
        @user = User.find(params[:user_id])
        @user.toggle!(:payed)
    end

   
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/inscriptions/new.html.erb
<h1 class="display-1 font-weight-bold text-light text-center mt-5 mb-3 title-shadow">J-B & Thom</h1>
<h2 class="display-4 text-light text-center mt-1 mb-5 title-shadow">Quarter Centuries</h2>
<h3 class="text-light text-center mt-1 mb-5 title-shadow">$$ Shaky Castle Party $$</h3>



<div class="numbers text-center " id="countdown" data-time="2021-12-04T18:30:00+0000">

    <div class="bloc text-light mb-5" >
        <strong id="days"></strong>
        <em>Jours</em>
    </div>

    <div class="bloc text-light" >
        <strong id="hours"></strong>
        <em>Heures</em>
    </div>

    <div class="bloc text-light" >
        <strong id="minutes"></strong>
        <em>Minutes</em>
    </div>

    <div class="bloc last text-light" >
        <strong id="seconds"></strong>
        <em>Secondes</em>
    </div>

</div>

<div class="card bg-form main-form ">
<%= form_with model: @user, local: true, url: inscription_path do |form| %>

    <% if @user.errors.any?%>
        <div class="alert alert-danger">
            <% @user.errors.full_messages.each do |message|%>
                <div><%= message %></div>
            <%end%>
        </div>
    <% end %>

    <div class="card-body">
        <div class="mb-4">
            <%=form.label :name, "Nom", class: "text-light"%>
            <%=form.text_field :name, class: "form-control", placeholder: "Macron" %>
        </div>
        <div class="mb-4">
            <%=form.label :first_name, "Prénom", class: "text-light"%>
            <%=form.text_field :first_name, class: "form-control", placeholder: "Emmanuel"  %>
        </div>
        <div class="mb-4">
            <%=form.label :email, "Adresse mail (on t'envoie les infos pratiques)",class: "form-label text-light"%>
            <%=form.text_field :email, class: "form-control", placeholder: "manuboss@monde.zob"  %>
        </div>
        <div class="mb-4 ml-4">
            <%=form.check_box :payed, class: "form-check-input " %>
            <%=form.label :payed, "IMPORTANT : J'ai bien compris que si je clique sur le bouton ci-dessous je m'engage à verser MAINTENANT la somme de 55€ sur la cagnotte Lydia prévu à cet effet pour aider au financement de la soirée.",class: "form-check-label text-light"%>
            
        </div>
        <div class="mb-5 d-flex justify-content-center">
            <%=form.submit "Je clique, je donne !", class: "btn btn-form text-light mt-4"%>
        </div>
    </div>
</div>
<% end %>


   

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Birthdayboys</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload', :defer => "defer" %>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">    

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <!-- favicon -->
     <%= favicon_link_tag asset_path('jib_16x16.ico') %>
  </head>

  <body class="house-pic">
    
    
    <div class="container">
    <%= yield %>
    </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_navbar.html.erb
<header>
    <a class="logo" href="#">JB 'n' T</a>
    <nav>
        <ul class="nav__links">
            <li><a href="#">Services</a></li>
            <li><a href="#">Work</a></li>
            <li><a href="#">Anniv</a></li>
        </ul>
    </nav>
    <a class="cta" href="#"><button>Contact</button></a>
</header>

app/views/user/index.html.erb
<h1 class="text-light text-center mt-5 mb-5"> ADMIN SYSTEM</h1>

<table class="table table-dark">



    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Nom</th>
            <th scope="col">Prénom</th>
            <th scope="col">Email</th>
            <th scope="col">À payé ?</th>
        </tr>
    </thead>



    <tbody>


        <% @user.each do |user| %>
    
            <tr>

                <th scope="row"><%= user.id %></th>

                <td><%= user.name %></td>

                <td><%= user.first_name %></td>

                <td><%= user.email %></td>

                <td class="user-<%= user.id %>">

                    <%= link_to "#{ user.payed ? 'à payé' : 'radin' }", user_toggle_payed_status_path(user), method: :patch, remote: :true, class: "btn ml-5 btn-#{ user.payed ? 'success' : 'danger' }"  %>

                    
                </td>

            </tr>
    
        <%end %>


    </tbody>
</table>

app/views/user/toggle_payed_status.js.erb
<% if @user.payed == true %>
    $(".user-<%= @user.id %> > a").html('à payé').removeClass('btn-danger').addClass('btn-success')
<% else %>
    $(".user-<%= @user.id %> > a").html('radin').removeClass('btn-success').addClass('btn-danger')
<% end %>
$("#user-status-<%= @user.id %>").html("<%= @user.payed %>")